// Central source of truth for the short explanations shown by <InfoTip>.
// Each entry's `href` points to the matching anchor on the Methodology page,
// which carries the longer version — keeps every other page from having to
// re-explain the same term.
export type GlossaryEntry = { text: string; href?: string };

export const GLOSSARY: Record<string, GlossaryEntry> = {
  core_coverage: {
    text: "The share of core skills the market demands for this program's relevant roles that its courses demonstrably cover, each skill counted equally regardless of demand. \"Core\" means the skill shows up in at least 5% of that role's job postings — rare, one-off requirements aren't counted against a program. A secondary, unweighted view — see weighted coverage for the dashboard's headline metric.",
    href: "/methodology#core-coverage",
  },
  weighted_coverage: {
    text: "This dashboard's headline score: like core coverage, but skills are weighted by how often employers ask for them, so covering a skill demanded in 20 postings counts more than covering one demanded in 3. Chosen as the headline because it's dominated by high-demand skills and stays comparatively stable as the job-market vocabulary grows, unlike the unweighted count.",
    href: "/methodology#core-coverage",
  },
  relevant_roles: {
    text: "The job-market role categories (e.g. Backend, Data / ML / AI) this program is compared against. Programs are scored only against roles relevant to them, not the entire IT job market.",
    href: "/methodology#pipeline",
  },
  doc_score: {
    text: "What fraction of this program's skills were extracted from clearly-written course descriptions, versus weakly-worded ones. A low score means gaps below may be documentation gaps — skills that are taught but not clearly described — rather than real curriculum gaps.",
    href: "/methodology#fairness",
  },
  gap_type: {
    text: "🔴 Curriculum gap = the skill is likely genuinely not taught. 🟡 Documentation gap = the skill may be taught but isn't clearly described in the course catalog, so it can't be verified. ⚪ Uncertain = not enough signal either way.",
    href: "/methodology#gaps",
  },
  curriculum_dataset: {
    text: "Course names, descriptions, and credit info published by each university, collected as a one-time snapshot. See the Methodology page for exact counts and dates.",
    href: "/methodology#data",
  },
  job_dataset: {
    text: "IT job postings collected from Armenian job boards and company career pages, used as a proxy for current market skill demand. See the Methodology page for exact counts and dates.",
    href: "/methodology#data",
  },
  ai_generated_description: {
    text: "This university didn't publish a written description for some courses — only a course name. For those, a short description was generated by AI from the course name and program context, then used the same way as a real description. This is disclosed here so a resulting score isn't mistaken for a hand-verified one.",
    href: "/methodology#fairness",
  },
  peer_average: {
    text: "The average weighted core coverage score among comparable programs at other Armenian universities (same degree level and, where possible, similar role focus) — a rough sense of how this program stacks up, not a ranking.",
  },
  experiment: {
    text: "Several different methods for extracting and matching skills were tested; the one shown throughout this dashboard performed best in evaluation. See Methodology for what was tried and why.",
    href: "/methodology#experiments",
  },
};
